version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: liquidity-optimization-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    container_name: liquidity-optimization-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
